#cloud-config

# Bootstrap configuration for K3S cluster nodes (master and worker)
# This file is generated by Tofu - DO NOT EDIT MANUALLY
# Template: bootstrap.yaml.tpl

# Automatic installation to available disk
install:
    auto: true
    device: auto
    reboot: true

# Hostname configuration
hostname: ${hostname}

# Network configuration
network:
    interfaces:
        eth0:
            addresses:
                - ${node_ip}/24
            dns_nameservers:
                - ${dns_server}
                - 8.8.8.8
            gateway: ${gateway}

# User configuration
users:
    - groups:
        - admin
        - sudo
        - docker
        - wheel
      name: kairos
      passwd: ${password_hash}
      shell: /bin/bash
      ssh_authorized_keys:
        - ${ssh_public_key}
      sudo: ALL=(ALL) NOPASSWD:ALL

